package data;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public abstract class PasswordEncryptor {
    /**
     * Used for hashing passwords
     * @param password Given password for a new user
     * @return hashcode generated by md5 algorithm
     */
    public static String hashPassword(String password) {
        try {
            MessageDigest messageDigest = MessageDigest.getInstance("MD5");
            byte[] hashed = messageDigest.digest(password.getBytes());
            return convertToString(hashed);
        } catch(NoSuchAlgorithmException e){
            e.printStackTrace();
        }

        return password;
    }

    /**
     * Helper method for hashing, turns byte array into a string
     * @param hash byte array generated by the hashing algorithm
     * @return String form of the hash
     */
    private static String convertToString(byte[] hash) {
        BigInteger no = new BigInteger(1, hash);
        StringBuilder hashSB = new StringBuilder(no.toString(16));

        while(hashSB.length() < 32) {
            hashSB.insert(0, "0");
        }

        return hashSB.toString();
    }

}
